// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	KEY_SETS: KVNamespace;
	REMOTE_JWKS: KVNamespace;
	CLIENT_AUTH_TOKENS: KVNamespace;
	PLATFORMS: KVNamespace;
	OIDC_STATE: DurableObjectNamespace<import("./src/index").OIDCStateDurableObject>;
	ASSETS: Fetcher;
}
